version: '3.8'
services:
  ct-service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER:  username
      POSTGRES_PASSWORD:  password
    ports:
      - "5433:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  ct-pgadmin:
    container_name: ct-pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ct-pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  ct-pgadmin-data:
