version: '2.32.2'
services:
  ct-client-backend:
    image: client:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ct-service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ct-service-db/calorie_tracker

  ct-service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER:  username
      POSTGRES_PASSWORD:  password
    ports:
      - "5433:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  ct-pgadmin:
    container_name: ct-pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5433", "-U", "username" ]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ct-pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  ct-pgadmin-data:
