server:
  port: 8080

spring:
  application:
    name: CalorieTracker
  datasource:
    url: jdbc:postgresql://localhost:5433/calorie_tracker
    username: username
    password: password
    driverClassname: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml





